export const subjects = [
  "Computer Programming and Problem Solving with C",
  "Data Structures in C",
  "Design and Analysis of Algorithms",
  "Database Management Systems",
  "Digital Electronics",
  "Computer Organization and Architecture",
  "System Software",
  "Operating Systems",
  "Theory of Computation",
  "Computer Networks",
  "An Introduction to Artificial Intelligence",
  "Software Engineering",
  "Object Oriented Analysis and Design",
  "Linear Algebra and Matrices",
  "Discrete Mathemtics",
  "Probability and Statistics",
  "Numerical Techniques",
  "Cryptography and Network Security",
  "Machine Learning",
  "Data Analytics and Visualization",
  "Topics in Security and Privacy",
  "Introduction to Metaverse",
  "5G Communication and Network"
];
