export const workData = [
  {
    duration: "January - May 2025",
    location: "IIIT Vadodara - ICD",
    type: "Teaching Assistant",
    role: "Basic Electrical Engineering",
    image: "/images/icd.png",
    alt: "image related to TAship",
    bg: "bg-green-50",
    href: "",
  },
  {
    duration: "September - December 2024",
    location: "Dhankhar Technologies Pvt. Ltd.",
    type: "Remote Internship",
    role: "Web Developer",
    image: "/images/icd.png",
    alt: "image related to internship",
    bg: "bg-blue-50",
    href: "",
  },
  {
    duration: "August - December 2024",
    location: "IIIT Vadodara - ICD",
    type: "Teaching Assistant",
    role: "Physics",
    image: "/images/icd.png",
    alt: "image related to TAship",
    bg: "bg-red-50",
    href: "",
  },
  {
    duration: "May 2023 - September 2024",
    location: "SAC, IIIT Vadodara - ICD",
    type: "Technical Committee",
    role: "Member",
    image: "/images/icd.png",
    alt: "image related to sac",
    bg: "bg-yellow-50",
    href: "",
  },
  {
    duration: "September 2023 - September 2024",
    location: "GDSC, IIIT Vadodara - ICD",
    type: "Volunteer",
    role: "Web Development Team",
    image: "/images/icd.png",
    alt: "image related to gdsc",
    bg: "bg-green-50",
    href: "",
  },
  // {
  //   duration: "December 2023 - January 2024",
  //   location: "Vadodara, Gujarat",
  //   type: "Social Media Engine",
  //   role: "Personal Project",
  //   image: "/images/icd.png",
  //   alt: "image related to stavya",
  //   bg: "bg-blue-50",
  //   href: "",
  // },
  // {
  //   duration: "December 2023 - January 2024",
  //   location: "SAC, IIIT Vadodara - ICD",
  //   type: "Stavya",
  //   role: "Web Developer",
  //   image: "/images/icd.png",
  //   alt: "image related to stavya",
  //   bg: "bg-red-50",
  //   href: "",
  // },
  // {
  //   duration: "January 2023 - February 2024",
  //   location: "SAC, IIIT Vadodara - ICD",
  //   type: "Horizon",
  //   role: "Web Developer",
  //   image: "/images/icd.png",
  //   alt: "image related to horizon",
  //   bg: "bg-green-50",
  //   href: "",
  // },
  // {
  //   duration: "September 2024 - November 2024",
  //   location: "IIIT Vadodara - ICD",
  //   type: "S.I.S. Scheme",
  //   role: "Design Project",
  //   image: "/images/icd.png",
  //   alt: "image related to gdsc",
  //   bg: "bg-yellow-50",
  //   href: "",
  // },
  // {
  //   duration: "September 2024 - November 2024",
  //   location: "IIIT Vadodara - ICD",
  //   type: "Neural Brawl",
  //   role: "Semester AI Project",
  //   image: "/images/icd.png",
  //   alt: "image related to stavya",
  //   bg: "bg-blue-50",
  //   href: "",
  // },
];
